generatorName: 'java'
groupId: 'aws.sample.blog.cdk-open-api'
artifactId: 'client'
apiPackage: 'aws.sample.blog.cdkopenapi.client.rest'
modelPackage: 'aws.sample.blog.cdkopenapi.client.rest.dto'
artifactVersion: '1.0.0-SNAPSHOT'
library: 'webclient'
#inputSpec: 'latestopenapi.json'
inputSpec: 'openapi.yaml'
outputDir: 'client'
java8: 'true'
